# Generated by Django 5.1.5 on 2025-07-12 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Events', 'Events'), ('Meetings', 'Meetings'), ('Festivals', 'Festivals'), ('Success Stories', 'Success Stories'), ('Trainings', 'Trainings'), ('Community Work', 'Community Work'), ('Others', 'Others')], default='Others', max_length=50)),
                ('gallery_image', models.ImageField(upload_to='Gallery_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
