# Generated by Django 5.1.5 on 2025-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_manpowergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowergallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
