# Generated by Django 5.1.5 on 2025-07-13 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_manpowergallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('unskilled', 'Unskilled'), ('semiskilled', 'Semi-skilled'), ('skilled', 'Skilled'), ('professional', 'Professional')], max_length=20)),
                ('job_image', models.ImageField(upload_to='Job_Images/')),
                ('job_description', models.TextField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
